const data = [
  { item: "Pile of Stickers", estimated_customs: "0", emoji: "stickers" },
  {
    item: "DigitalOcean credits",
    estimated_customs: "0",
    emoji: "digitalocean",
  },
  { item: "OpenAI credits", estimated_customs: "0", emoji: "openai" },
  { item: "Hetzner credits", estimated_customs: "0", emoji: "hetzner" },
  { item: "Anthropic Credits", estimated_customs: "0", emoji: "anthropic" },
  {
    item: "Hack Club MicroSD card",
    estimated_customs: "0-200",
    emoji: "microsd",
  },
  { item: "Logic Analyzer", estimated_customs: "0", emoji: "logic" },
  {
    item: "Bite Size Linux",
    estimated_customs: "0-200",
    emoji: "bite_size_linux",
  },
  {
    item: "Bite Size Bash",
    estimated_customs: "0-200",
    emoji: "bite_size_bash",
  },
  { item: "How DNS Works", estimated_customs: "0-200", emoji: "dns" },
  { item: "Domain (1 year)", estimated_customs: "0", emoji: "domain" },
  { item: "Raspberry Pi", estimated_customs: "0-3000", emoji: "rpi" },
  { item: "Digital Calipers", estimated_customs: "UNSURE", emoji: "calipers" },
  { item: "PCB manufacturing credit", estimated_customs: "0", emoji: "pcb" },
  { item: "Hot Glue Gun", estimated_customs: "0", emoji: "glue" },
  { item: "DigiKey/LCSC Credit", estimated_customs: "0", emoji: null },
  { item: "GitHub Invertocat Pin", estimated_customs: "0-700", emoji: "ghpin" },
  { item: "Pinecil", estimated_customs: "1500-3500", emoji: "pinecil" },
  { item: "GitHub Notebook", estimated_customs: "0", emoji: "ghnotebook" },
  { item: "Baofeng UV-5R", estimated_customs: "UNSURE", emoji: "baofeng" },
  { item: "Lockpick set", estimated_customs: "500-2500", emoji: "lockpick" },
  { item: "GitHub Keycaps", estimated_customs: "500-2500", emoji: "keycaps" },
  { item: "Hack Club socks", estimated_customs: "500-2500", emoji: "socks" },
  {
    item: "GitHub Universe Badge",
    estimated_customs: "0-6000",
    emoji: "ghunibadge",
  },
  { item: "YubiKey", estimated_customs: "0", emoji: "yubikey" },
  { item: "Dremel 4300 kit", estimated_customs: "UNSURE", emoji: "dremel" },
  { item: "Raspberry Pi 5", estimated_customs: "5000-12000", emoji: "rpi5" },
  {
    item: "System76 Launch Keyboard",
    estimated_customs: "5000-15000",
    emoji: null,
  },
  {
    item: "GitHub MiiR® Backpack",
    estimated_customs: "5000-15000",
    emoji: "ghbackpack",
  },
  {
    item: "Bambu Lab A1 Mini",
    estimated_customs: "20000-50000+",
    emoji: "bambu_a1_mini",
  },
  { item: "iPad", estimated_customs: "0", emoji: "ipad" },
  { item: 'MacBook Air M2 13"', estimated_customs: "UNSURE", emoji: "macbook" },
  { item: "Ticket to DEF CON", estimated_customs: "0", emoji: "defcon" },
].map((d) => ({
  ...d,
  emoji: d.emoji ? `:highseas-shop-${d.emoji}: ` : d.emoji,
}));
module.exports = data;
