const data = [
  { item: "Pile of Stickers", estimated_customs: "0" },
  { item: "DigitalOcean credits", estimated_customs: "0" },
  { item: "OpenAI credits", estimated_customs: "0" },
  { item: "Hetzner credits", estimated_customs: "0" },
  { item: "Anthropic Credits", estimated_customs: "0" },
  { item: "Hack Club MicroSD card", estimated_customs: "0-200" },
  { item: "Logic Analyzer", estimated_customs: "0" },
  { item: "Bite Size Linux", estimated_customs: "0-200" },
  { item: "Bite Size Bash", estimated_customs: "0-200" },
  { item: "How DNS Works", estimated_customs: "0-200" },
  { item: "Domain (1 year)", estimated_customs: "0" },
  { item: "Raspberry Pi", estimated_customs: "0-3000" },
  { item: "Digital Calipers", estimated_customs: "UNSURE" },
  { item: "PCB manufacturing credit", estimated_customs: "0" },
  { item: "Hot Glue Gun", estimated_customs: "0" },
  { item: "DigiKey/LCSC Credit", estimated_customs: "0" },
  { item: "GitHub Invertocat Pin", estimated_customs: "0-700" },
  { item: "Pinecil", estimated_customs: "1500-3500" },
  { item: "GitHub Notebook", estimated_customs: "0" },
  { item: "Baofeng UV-5R", estimated_customs: "UNSURE" },
  { item: "Lockpick set", estimated_customs: "500-2500" },
  { item: "GitHub Keycaps", estimated_customs: "500-2500" },
  { item: "Hack Club socks", estimated_customs: "500-2500" },
  { item: "GitHub Universe Badge", estimated_customs: "0-6000" },
  { item: "YubiKey", estimated_customs: "0" },
  { item: "Dremel 4300 kit", estimated_customs: "UNSURE" },
  { item: "Raspberry Pi 5", estimated_customs: "5000-12000" },
  { item: "System76 Launch Keyboard", estimated_customs: "5000-15000" },
  { item: "GitHub MiiR® Backpack", estimated_customs: "5000-15000" },
  { item: "Bambu Lab A1 Mini", estimated_customs: "20000-50000+" },
  { item: "iPad", estimated_customs: "0" },
  { item: 'MacBook Air M2 13"', estimated_customs: "UNSURE" },
  { item: "Ticket to DEF CON", estimated_customs: "0" },
];
